// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezbzvoxttkcfuuktfwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllemJ6dm94dHRrY2Z1dWt0ZndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjMzNTMsImV4cCI6MjA5MDAzOTM1M30.PG29VKMmhMLPtPuqXidLKTvIgVJvWCe9JBP-UA7O60c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});